/* Copyright (c) 2025 by InterSystems Corporation.
   Cambridge, Massachusetts, U.S.A.  All rights reserved.
   Confidential property of InterSystems Corporation. */

/// Stream that contains raw bytes of data. No character mapping is applied; any similarity of the data to characters is purely coincidental.
Class %IO.I.ByteStream Extends (%IO.I.Stream, %IO.IParts.ByteIO) [ Abstract, Inheritance = right, System = 2 ]
{

}
