/* Copyright (c) 2025 by InterSystems Corporation.
   Cambridge, Massachusetts, U.S.A.  All rights reserved.
   Confidential property of InterSystems Corporation. */

/// This is an internal datatype used to represent OREF values.
/// <p>User applications should not use this data type.
Class %Library.ObjectHandle [ ClassType = datatype, ClientDataType = HANDLE, OdbcType = INTEGER, Not ProcedureBlock, SqlCategory = INTEGER, System = 2 ]
{

}
