/* Copyright (c) 2025 by InterSystems Corporation.
   Cambridge, Massachusetts, U.S.A.  All rights reserved.
   Confidential property of InterSystems Corporation. */

Class %ZEN.Report.Display.COSChart.extent Extends %RegisteredObject [ Deprecated, System = 4 ]
{

Property minX As %Double;

Property minY As %Double;

Property maxX As %Double;

Property maxY As %Double;

Property w As %Double;

Property h As %Double;

}
