/* Copyright (c) 2025 by InterSystems Corporation.
   Cambridge, Massachusetts, U.S.A.  All rights reserved.
   Confidential property of InterSystems Corporation. */

/// Simple SVG spacer component.<br>
/// This is a simple spacer component that can be used within
/// an SVG frame as a way to insert additional space within a layout.
Class %ZEN.SVGComponent.svgSpacer Extends svgComponent [ Deprecated, System = 3 ]
{

}
