/* Copyright (c) 2025 by InterSystems Corporation.
   Cambridge, Massachusetts, U.S.A.  All rights reserved.
   Confidential property of InterSystems Corporation. */

/// This is a string containing an HTML horizontal alignment value.
Class %ZEN.Datatype.align Extends datatype [ Deprecated, System = 3 ]
{

Parameter XMLPROJECTION = "attribute";

Parameter MAXLEN = 25;

Parameter VALUELIST = ",left,right,center";

}
